if UnitClassBase("player") ~= "DEMONHUNTER" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "恶魔之怒" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "敌人人数" },
        [22] = { type = "block", name = "目标施法" },
        [23] = { type = "block", name = "目标施法可打断" },
        [24] = { type = "block", name = "焦点施法" },
        [25] = { type = "block", name = "焦点施法可打断" },
        [26] = { type = "block", name = "目标引导" },
        [27] = { type = "block", name = "目标引导可打断" },
        [28] = { type = "block", name = "焦点引导" },
        [29] = { type = "block", name = "焦点引导可打断" },
        [40] = { type = "spell", spellId = 196718, name = "黑暗" },
        [41] = { type = "spell", spellId = 198793, name = "复仇回避" },
        [42] = { type = "spell", spellId = 185123, name = "投掷利刃 " },
        [43] = { type = "spell", spellId = 185123, name = "投掷利刃", charge = true },
        [44] = { type = "spell", spellId = 207684, name = "悲苦咒符" },
        [45] = { type = "spell", spellId = 217832, name = "禁锢" },
        [46] = { type = "spell", spellId = 258920, name = "献祭光环" },
        [47] = { type = "spell", spellId = 179057, name = "混乱新星" },
        [48] = { type = "spell", spellId = 191427, name = "恶魔变形" },
        [49] = { type = "spell", spellId = 232893, name = "邪能之刃" },
        [50] = { type = "spell", spellId = 188499, name = "刃舞" },
        [51] = { type = "spell", spellId = 162794, name = "混乱打击" },
        [52] = { type = "spell", spellId = 198589, name = "疾影" },
        [53] = { type = "spell", spellId = 370965, name = "恶魔追击" },
        [54] = { type = "spell", spellId = 198013, name = "眼棱" },
        [55] = { type = "spell", spellId = 195072, name = "邪能冲撞" },
        [56] = { type = "spell", spellId = 258860, name = "精华破碎" },
    },
    [2] = {
        ["countBars"] = {
            { valueType = "castCount", name = "灵魂裂劈", minValue = 0, maxValue = 6, spellId = 228477 },
            { valueType = "charge", name = "投掷利刃", minValue = 0, maxValue = 2, spellId = 185123 },
            { valueType = "charge", name = "地狱火撞击", minValue = 0, maxValue = 2, spellId = 189110 },
            { valueType = "charge", name = "烈火烙印", minValue = 0, maxValue = 2, spellId = 204021 },
            { valueType = "charge", name = "破裂", minValue = 0, maxValue = 2, spellId = 263642 },
        },
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "恶魔之怒" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "敌人人数" },
        [22] = { type = "block", name = "防御光环" },
        [23] = { type = "block", name = "目标施法" },
        [24] = { type = "block", name = "目标引导" },
        [25] = { type = "block", name = "焦点施法" },
        [26] = { type = "block", name = "焦点引导" },
        [27] = { type = "block", name = "目标施法可打断" },
        [28] = { type = "block", name = "目标引导可打断" },
        [29] = { type = "block", name = "焦点施法可打断" },
        [30] = { type = "block", name = "焦点引导可打断" },
        [31] = { type = "aura", name = "无羁邪怒", auraName = "无羁邪怒", showKey = "remaining" },
        [40] = { type = "spell", spellId = 196718, name = "黑暗" },
        [41] = { type = "spell", spellId = 198793, name = "复仇回避" },
        [42] = { type = "spell", spellId = 185123, name = "投掷利刃 " },
        [43] = { type = "spell", spellId = 185123, name = "投掷利刃", charge = true },
        [44] = { type = "spell", spellId = 207684, name = "悲苦咒符" },
        [45] = { type = "spell", spellId = 217832, name = "禁锢" },
        [46] = { type = "spell", spellId = 258920, name = "献祭光环" },
        [47] = { type = "spell", spellId = 179057, name = "混乱新星" },
        [48] = { type = "spell", spellId = 187827, name = "恶魔变形" },
        [49] = { type = "spell", spellId = 232893, name = "邪能之刃" },
        [50] = { type = "spell", spellId = 189110, name = "地狱火撞击" },
        [51] = { type = "spell", spellId = 189110, name = "地狱火撞击", charge = true },
        [52] = { type = "spell", spellId = 203720, name = "恶魔尖刺" },
        [53] = { type = "spell", spellId = 204021, name = "烈火烙印" },
        [54] = { type = "spell", spellId = 204021, name = "烈火烙印", charge = true },
        [55] = { type = "spell", spellId = 247454, name = "幽魂炸弹" },
        [56] = { type = "spell", spellId = 207407, name = "灵魂切削" },
        [57] = { type = "spell", spellId = 204596, name = "烈焰咒符" },
        [58] = { type = "spell", spellId = 390163, name = "怨念咒符" },
        [59] = { type = "spell", spellId = 228447, name = "灵魂裂劈" },
        [60] = { type = "spell", spellId = 263642, name = "破裂" },
        [61] = { type = "spell", spellId = 263642, name = "破裂", charge = true },
        [62] = { type = "spell", spellId = 212084, name = "邪能毁灭" },
        [63] = { type = "spell", spellId = 202137, name = "沉默咒符" },
    },
    [3] = {
        ["countBars"] = {
            { valueType = "castCount", name = "灵魂残片", minValue = 0, maxValue = 50, spellId = 1217605 },
        },
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "恶魔之怒" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "敌人人数" },
        [22] = { type = "block", name = "目标施法" },
        [23] = { type = "block", name = "目标施法可打断" },
        [24] = { type = "block", name = "焦点施法" },
        [25] = { type = "block", name = "焦点施法可打断" },
        [26] = { type = "block", name = "目标引导" },
        [27] = { type = "block", name = "目标引导可打断" },
        [28] = { type = "block", name = "焦点引导" },
        [29] = { type = "block", name = "焦点引导可打断" },
        [40] = { type = "spell", spellId = 196718, name = "黑暗" },
        [41] = { type = "spell", spellId = 198793, name = "复仇回避" },
        [42] = { type = "spell", spellId = 185123, name = "投掷利刃 " },
        [43] = { type = "spell", spellId = 185123, name = "投掷利刃", charge = true },
        [44] = { type = "spell", spellId = 207684, name = "悲苦咒符" },
        [45] = { type = "spell", spellId = 217832, name = "禁锢" },
        [46] = { type = "spell", spellId = 258920, name = "献祭光环" },
        [47] = { type = "spell", spellId = 1234195, name = "虚空新星" },
        [48] = { type = "spell", spellId = 1217605, name = "虚空变形" },
        [49] = { type = "spell", spellId = 1245412, name = "虚空之刃" },
        [50] = { type = "spell", spellId = 1234796, name = "变换 " },
        [51] = { type = "spell", spellId = 1234796, name = "变换", charge = true },
        [52] = { type = "spell", spellId = 1226019, name = "收割" },
        [53] = { type = "spell", spellId = 473662, name = "吞噬" },
        [54] = { type = "spell", spellId = 198589, name = "疾影" },
        [55] = { type = "spell", spellId = 473728, name = "虚空射线" },
        [56] = { type = "spell", spellId = 1246167, name = "恶魔追击" },
        [57] = { type = "spell", spellId = 1239123, name = "饥渴斩击" },
        [58] = { type = "spell", spellId = 1245453, name = "剔除" },
    },
}
Fuyutsui.MacrosList = {
    dynamicSpells = {},
    specialSpells = {
        [19] = "/castsequence reset=0.5 烈火烙印,x",
        [16] = "/castsequence reset=0.5 恶魔变形,x",
    },
    staticSpells = {
        [1] = "复仇回避",
        [2] = "投掷利刃",
        [3] = "[@cursor]悲苦咒符",
        [4] = "禁锢",
        [5] = "献祭光环",
        [6] = "混乱新星",
        [7] = "恶魔变形",
        [8] = "邪能之刃",
        [9] = "刃舞",
        [10] = "混乱打击",
        [11] = "疾影",
        [12] = "恶魔追击",
        [13] = "眼棱",
        [14] = "邪能冲撞",
        [15] = "精华破碎",
        -- [16] = "恶魔变形",
        [17] = "地狱火撞击",
        [18] = "恶魔尖刺",
        -- [19] = "烈火烙印",
        [20] = "幽魂炸弹",
        [21] = "灵魂切削",
        [22] = "[@player]烈焰咒符",
        [23] = "[@player]怨念咒符",
        [24] = "灵魂裂劈",
        [25] = "破裂",
        [26] = "邪能毁灭",
        [27] = "[@cursor]沉默咒符",
        [28] = "虚空新星",
        [29] = "虚空变形",
        [30] = "虚空之刃",
        [31] = "变换",
        [32] = "收割",
        [33] = "吞噬",
        [34] = "虚空射线",
        [35] = "恶魔追击",
        [36] = "饥渴斩击",
        [37] = "黑暗",
    },
}
