if UnitClassBase("player") ~= "DRUID" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "能量值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "目标生命值" },
        [22] = { type = "block", name = "敌人人数" },
        [23] = { type = "block", name = "姿态" },
        [31] = { type = "spell", spellId = 22812, name = "树皮术" },
        [32] = { type = "spell", spellId = 132469, name = "台风" },
        [33] = { type = "spell", spellId = 99, name = "夺魂咆哮" },
        [34] = { type = "spell", spellId = 29166, name = "激活" },
        [35] = { type = "spell", spellId = 102793, name = "乌索尔旋风" },
        [36] = { type = "spell", spellId = 78675, name = "日光术" },
        [37] = { type = "block", name = "目标施法" },
        [38] = { type = "block", name = "目标施法可打断" },
        [39] = { type = "block", name = "焦点施法" },
        [40] = { type = "block", name = "焦点施法可打断" },
        [41] = { type = "block", name = "目标引导" },
        [42] = { type = "block", name = "目标引导可打断" },
        [43] = { type = "block", name = "焦点引导" },
        [44] = { type = "block", name = "焦点引导可打断" },
    },
    [2] = {
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "能量值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "目标生命值" },
        [22] = { type = "block", name = "敌人人数" },
        [23] = { type = "block", name = "姿态" },
        [31] = { type = "spell", spellId = 22812, name = "树皮术" },
        [32] = { type = "spell", spellId = 132469, name = "台风" },
        [33] = { type = "spell", spellId = 99, name = "夺魂咆哮" },
        [34] = { type = "spell", spellId = 29166, name = "激活" },
        [35] = { type = "spell", spellId = 102793, name = "乌索尔旋风" },
        [37] = { type = "block", name = "目标施法" },
        [38] = { type = "block", name = "目标施法可打断" },
        [39] = { type = "block", name = "焦点施法" },
        [40] = { type = "block", name = "焦点施法可打断" },
        [41] = { type = "block", name = "目标引导" },
        [42] = { type = "block", name = "目标引导可打断" },
        [43] = { type = "block", name = "焦点引导" },
        [44] = { type = "block", name = "焦点引导可打断" },
    },
    [3] = {
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "能量值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "目标生命值" },
        [22] = { type = "block", name = "敌人人数" },
        [23] = { type = "block", name = "姿态" },
        [24] = { type = "aura", name = "塞纳留斯的梦境", auraName = "塞纳留斯的梦境", showKey = "remaining" },
        [25] = { type = "aura", name = "塞纳留斯的梦境层数", auraName = "塞纳留斯的梦境", showKey = "count" },
        [26] = { type = "aura", name = "铁鬃", auraName = "铁鬃", showKey = "remaining" },
        [27] = { type = "aura", name = "狂暴回复", auraName = "狂暴回复", showKey = "remaining" },
        [28] = { type = "aura", name = "星河守护者", auraName = "星河守护者", showKey = "remaining" },
        [29] = { type = "aura", name = "淤血", auraName = "淤血", showKey = "remaining" },
        [31] = { type = "spell", spellId = 22812, name = "树皮术" },
        [32] = { type = "spell", spellId = 132469, name = "台风" },
        [33] = { type = "spell", spellId = 99, name = "夺魂咆哮" },
        [34] = { type = "spell", spellId = 29166, name = "激活" },
        [35] = { type = "spell", spellId = 102793, name = "乌索尔旋风" },
        [36] = { type = "spell", spellId = 22842, name = "狂暴回复" },
        [37] = { type = "spell", spellId = 22842, name = "狂暴回复", charge = true },
        [38] = { type = "spell", spellId = 61336, name = "生存本能" },
        [39] = { type = "spell", spellId = 102558, name = "化身：乌索克的守护者" },
        [40] = { type = "spell", spellId = 1261867, name = "野性之心" },
        [41] = { type = "spell", spellId = 1253799, name = "碎甲咆哮" },
        [42] = { type = "spell", spellId = 1252871, name = "赤红之月" },
        [43] = { type = "spell", spellId = 6807, name = "重殴" },
        [44] = { type = "spell", spellId = 77758, name = "痛击" },
        [45] = { type = "block", name = "目标施法" },
        [46] = { type = "block", name = "目标施法可打断" },
        [47] = { type = "block", name = "焦点施法" },
        [48] = { type = "block", name = "焦点施法可打断" },
        [49] = { type = "block", name = "目标引导" },
        [50] = { type = "block", name = "目标引导可打断" },
        [51] = { type = "block", name = "焦点引导" },
        [52] = { type = "block", name = "焦点引导可打断" },
    },
    [4] = {
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "法力值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "姿态" },
        [22] = { type = "block", name = "目标距离" },
        [23] = { type = "block", name = "连击点" },
        [24] = { type = "block", name = "施法技能" },
        [25] = { type = "block", name = "目标施法" },
        [26] = { type = "block", name = "目标施法可打断" },
        [29] = { type = "aura", name = "节能施法", auraName = "节能施法", showKey = "remaining" },
        [30] = { type = "aura", name = "丛林之魂", auraName = "丛林之魂", showKey = "remaining" },
        [31] = { type = "spell", spellId = 22812, name = "树皮术" },
        [32] = { type = "spell", spellId = 132469, name = "台风" },
        [33] = { type = "spell", spellId = 99, name = "夺魂咆哮" },
        [34] = { type = "spell", spellId = 29166, name = "激活" },
        [35] = { type = "spell", spellId = 102793, name = "乌索尔旋风" },
        [36] = { type = "spell", spellId = 18562, name = "迅捷治愈" },
        [37] = { type = "spell", spellId = 18562, name = "迅捷治愈", charge = true },
        [38] = { type = "spell", spellId = 48438, name = "野性成长" },
        [39] = { type = "spell", spellId = 391528, name = "万灵之召" },
        [40] = { type = "spell", spellId = 88423, name = "自然之愈" },
        [41] = { type = "spell", spellId = 102342, name = "铁木树皮" },
        [42] = { type = "spell", spellId = 132158, name = "自然迅捷" },
        [43] = { type = "spell", spellId = 1261867, name = "野性之心" },
        [45] = {
            type = "group",
            num = 7,
            healthPercent = 1,
            role = 2,
        },
    },
}
Fuyutsui.MacrosList = {
    dynamicSpells = { "回春术", "愈合", "生命绽放", "迅捷治愈", "自然之愈" },
    specialSpells = {
        [17] = "/cancelaura [spec:4]猎豹形态\n/cast 万灵之召",
        [22] = "/castsequence reset=0.5 铁鬃,x"
    },
    staticSpells = {
        [1]  = "[nostance:2]猎豹形态(变形)",
        [2]  = "[nostance:1]熊形态(变形)",
        [3]  = "[nostance:4]枭兽形态",
        [4]  = "月火术",
        [5]  = "树皮术",
        [6]  = "横扫",
        [7]  = "潜行",
        [8]  = "凶猛撕咬",
        [9]  = "愤怒",
        [10] = "割裂",
        [11] = "撕碎",
        [12] = "斜掠",
        [13] = "痛击",
        [14] = "野性印记",
        [15] = "裂伤",
        [16] = "野性成长",
        [18] = "自然迅捷",
        [19] = "[@player]激活",
        [20] = "野性之心",
        [21] = "野性冲锋",
        -- [22] = "铁鬃",
        [23] = "摧折",
        [24] = "明月普照",
        [25] = "狂暴回复",
        [26] = "台风",
        [27] = "夺魂咆哮",
        [28] = "[@cursor]乌索尔旋风",
        [29] = "日光术",
        [30] = "星涌术",
        [31] = "星火术",
        [32] = "星辰坠落",
        [33] = "自然之力",
        [34] = "日蚀",
        [35] = "超凡之盟",
        [36] = "化身：艾露恩之眷",
        [37] = "艾露恩之怒",
        [38] = "野性蘑菇",
        [39] = "新月",
        [40] = "阳炎术",
        [41] = "月蚀",
        [42] = "化身：阿莎曼之灵",
        [43] = "原始之怒",
        [44] = "迎头痛击",
        [45] = "怒意狂乱",
        [46] = "猛虎之怒",
        [47] = "生存本能",
        [48] = "野性冲锋",
        [49] = "群体缠绕",
        [50] = "狂暴",
        [51] = "啃噬",
        [52] = "野性狂乱",
        [53] = "碎甲咆哮",
        [54] = "重殴",
    },
}
