if UnitClassBase("player") ~= "MONK" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        ["countBars"] = {
            { valueType = "castCount", name = "疗伤珠", minValue = 0, maxValue = 10, spellId = 322101 },
        },

        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "能量值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "酒池" },
        [22] = { type = "block", name = "目标生命值" },
        [23] = { type = "block", name = "敌人人数" },
        [25] = { type = "aura", name = "疗伤珠", auraName = "疗伤珠", showKey = "count" },
        [26] = { type = "aura", name = "活力苏醒", auraName = "活力苏醒", showKey = "remaining" },
        [27] = { type = "aura", name = "清空地窖", auraName = "清空地窖", showKey = "remaining" },
        [31] = { type = "spell", spellId = 121253, name = "醉酿投" },
        [32] = { type = "spell", spellId = 121253, name = "醉酿投", charge = true },
        [33] = { type = "spell", spellId = 119582, name = "活血酒" },
        [34] = { type = "spell", spellId = 119582, name = "活血酒", charge = true },
        [35] = { type = "spell", spellId = 322507, name = "天神酒" },
        [36] = { type = "spell", spellId = 322507, name = "天神酒", charge = true },
        [37] = { type = "spell", spellId = 1241059, name = "天神灌注" },
        [38] = { type = "spell", spellId = 1241059, name = "天神灌注", charge = true },
        [39] = { type = "spell", spellId = 322109, name = "轮回之触" },
        [40] = { type = "spell", spellId = 119381, name = "扫堂腿" },
        [41] = { type = "spell", spellId = 322101, name = "移花接木" },
        [42] = { type = "spell", spellId = 101643, name = "魂体双分" },
        [43] = { type = "spell", spellId = 119996, name = "魂体双分：转移" },
        [44] = { type = "spell", spellId = 116705, name = "切喉手" },
        [45] = { type = "spell", spellId = 115181, name = "火焰之息" },
        [46] = { type = "spell", spellId = 123986, name = "真气爆裂" },
        [47] = { type = "spell", spellId = 325153, name = "爆炸酒桶" },
        [48] = { type = "spell", spellId = 198898, name = "赤精之歌" },
        [49] = { type = "spell", spellId = 115399, name = "玄牛酒" },
        [50] = { type = "spell", spellId = 116844, name = "平心之环" },
        [51] = { type = "spell", spellId = 115078, name = "分筋错骨" },
        [52] = { type = "spell", spellId = 132578, name = "玄牛下凡" },
        [53] = { type = "spell", spellId = 205523, name = "幻灭踢" },
        [54] = { type = "block", name = "目标施法" },
        [55] = { type = "block", name = "目标施法可打断" },
        [56] = { type = "block", name = "焦点施法" },
        [57] = { type = "block", name = "焦点施法可打断" },
        [58] = { type = "block", name = "目标引导" },
        [59] = { type = "block", name = "目标引导可打断" },
        [60] = { type = "block", name = "焦点引导" },
        [61] = { type = "block", name = "焦点引导可打断" },
    },
    [2] = {
        ["countBars"] = {
            { valueType = "castCount", name = "法力茶", minValue = 0, maxValue = 20, spellId = 115294 },
            { valueType = "castCount", name = "神龙之赐", minValue = 0, maxValue = 10, spellId = 399491 },
        },

        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "法力值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "敌人人数" },
        [22] = { type = "block", name = "施法技能" },
        [23] = { type = "block", name = "施法目标" },
        [49] = { type = "block", name = "目标距离" },
        [50] = { type = "block", name = "爆发开关" },
        [51] = { type = "block", name = "目标施法" },
        [52] = { type = "block", name = "目标施法可打断" },
        [25] = { type = "aura", name = "生生不息1", auraName = "生生不息1", showKey = "remaining" },
        [26] = { type = "aura", name = "生生不息2", auraName = "生生不息2", showKey = "remaining" },
        [28] = { type = "aura", name = "灵泉", auraName = "灵泉", showKey = "remaining" },
        [29] = { type = "aura", name = "玄牛之力", auraName = "玄牛之力", showKey = "remaining" },
        [30] = { type = "aura", name = "青龙之心", auraName = "青龙之心", showKey = "remaining" },
        [48] = { type = "aura", name = "活力苏醒", auraName = "活力苏醒", showKey = "remaining" },
        [31] = { type = "spell", spellId = 116680, name = "雷光聚神茶" },
        [32] = { type = "spell", spellId = 116680, name = "雷光聚神茶", charge = true },
        [33] = { type = "spell", spellId = 115151, name = "复苏之雾" },
        [34] = { type = "spell", spellId = 115151, name = "复苏之雾", charge = true },
        [35] = { type = "spell", spellId = 115310, name = "还魂术" },
        [36] = { type = "spell", spellId = 116849, name = "作茧缚命" },
        [37] = { type = "spell", spellId = 115450, name = "清创生血" },
        [38] = { type = "spell", spellId = 443028, name = "天神御身" },
        [39] = { type = "spell", spellId = 322109, name = "轮回之触" },
        [40] = { type = "spell", spellId = 119381, name = "扫堂腿" },
        [41] = { type = "spell", spellId = 1270621, name = "宁神茶" },
        [42] = { type = "spell", spellId = 101643, name = "魂体双分" },
        [43] = { type = "spell", spellId = 119996, name = "魂体双分：转移" },
        [44] = { type = "spell", spellId = 107428, name = "旭日东升踢" },
        [45] = { type = "spell", spellId = 100784, name = "幻灭踢" },
        [46] = { type = "spell", spellId = 116844, name = "平心之环" },
        [47] = { type = "spell", spellId = 115078, name = "分筋错骨" },
        [70] = {
            type = "group",
            num = 5,
            healthPercent = 1,
            role = 2,
        },
    },
    [3] = {
        ["countBars"] = {
            { valueType = "charge", name = "乾元之巅", minValue = 0, maxValue = 2, spellId = 1249625 },
        },
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "能量值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "目标生命值" },
        [22] = { type = "block", name = "敌人人数" },
        [23] = { type = "block", name = "真气" },

        [24] = { type = "spell", spellId = 122470, name = "业报之触" },
        [25] = { type = "spell", spellId = 107428, name = "旭日东升踢" },
        [26] = { type = "spell", spellId = 1249625, name = "乾元之巅" },
        [27] = { type = "spell", spellId = 218164, name = "清创生血" },
        [28] = { type = "spell", spellId = 152175, name = "升龙霸" },
        [29] = { type = "spell", spellId = 101545, name = "翔龙在天" },
        [30] = { type = "spell", spellId = 113656, name = "怒雷破" },


        [31] = { type = "spell", spellId = 322109, name = "轮回之触" },
        [32] = { type = "spell", spellId = 119381, name = "扫堂腿" },
        [33] = { type = "spell", spellId = 322101, name = "移花接木" },
        [34] = { type = "spell", spellId = 101643, name = "魂体双分" },
        [35] = { type = "spell", spellId = 119996, name = "魂体双分：转移" },
        [36] = { type = "spell", spellId = 116705, name = "切喉手" },
        [37] = { type = "spell", spellId = 198898, name = "赤精之歌" },
        [38] = { type = "spell", spellId = 116844, name = "平心之环" },
        [39] = { type = "spell", spellId = 115078, name = "分筋错骨" },

        [41] = { type = "block", name = "目标施法" },
        [42] = { type = "block", name = "目标施法可打断" },
        [43] = { type = "block", name = "焦点施法" },
        [44] = { type = "block", name = "焦点施法可打断" },
        [45] = { type = "block", name = "目标引导" },
        [46] = { type = "block", name = "目标引导可打断" },
        [47] = { type = "block", name = "焦点引导" },
        [48] = { type = "block", name = "焦点引导可打断" },
    },
}
Fuyutsui.MacrosList = {
    dynamicSpells = { "氤氲之雾", "活血术", "清创生血", "抚慰之雾", "复苏之雾", "作茧缚命" },
    specialSpells = {},
    staticSpells = {
        [1] = "扫堂腿",
        [2] = "神鹤引项踢",
        [3] = "壮胆酒",
        [4] = "[known:116844,@cursor]平心之环;[known:198898]赤精之歌",
        [5] = "猛虎掌",
        [6] = "轮回之触",
        [7] = "幻灭踢",
        [8] = "碎玉闪电",
        [9] = "切喉手",
        [10] = "天神灌注",
        [11] = "火焰之息",
        [12] = "活血酒",
        [13] = "[@player]爆炸酒桶",
        [14] = "玄牛下凡",
        [15] = "醉酿投",
        [16] = "真气爆裂",
        [17] = "天神酒",
        [18] = "移花接木",
        [19] = "魂体双分",
        [20] = "魂体双分：转移",
        [21] = "雷光聚神茶",
        [22] = "法力茶",
        [23] = "旭日东升踢",
        [24] = "天神御身",
        [25] = "分筋错骨",
        [26] = "风领主之击",
        [27] = "怒雷破",
        [28] = "升龙霸",
    },
}
