if UnitClassBase("player") ~= "MONK" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "施法",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "酒池",
                "敌人数量",
            },
            ["能量"] = {
                "能量值",
            },
            ["目标"] = {
                "类型",
                "生命值",
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["焦点"] = {
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
        },
        -- TODO spellId: 疗伤珠
        -- TODO spellId: 活力苏醒
        -- TODO spellId: 清空地窖
        spells = {
            { spellId = 121253, name = "醉酿投", charge = true },
            { spellId = 119582, name = "活血酒", charge = true },
            { spellId = 322507, name = "天神酒", charge = true },
            { spellId = 1241059, name = "天神灌注", charge = true },
            { spellId = 322109, name = "轮回之触" },
            { spellId = 119381, name = "扫堂腿" },
            { spellId = 322101, name = "移花接木", castCount = 10 },
            { spellId = 101643, name = "魂体双分" },
            { spellId = 119996, name = "魂体双分：转移" },
            { spellId = 116705, name = "切喉手" },
            { spellId = 115181, name = "火焰之息" },
            { spellId = 123986, name = "真气爆裂" },
            { spellId = 325153, name = "爆炸酒桶" },
            { spellId = 198898, name = "赤精之歌" },
            { spellId = 115399, name = "玄牛酒" },
            { spellId = 116844, name = "平心之环" },
            { spellId = 115078, name = "分筋错骨" },
            { spellId = 132578, name = "玄牛下凡" },
            { spellId = 205523, name = "幻灭踢" },
        },
    },
    [2] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "施法",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "敌人数量",
                "施法技能",
                "施法目标",
            },
            ["能量"] = {
                "法力值",
            },
            ["配置开关"] = {
                "爆发开关",
            },
            ["目标"] = {
                "类型",
                "距离",
                "施法",
                "施法可打断",
            },
        },
        -- TODO spellId: 生生不息1
        -- TODO spellId: 生生不息2
        -- TODO spellId: 灵泉
        -- TODO spellId: 玄牛之力
        -- TODO spellId: 青龙之心
        -- TODO spellId: 活力苏醒
        spells = {
            { spellId = 116680, name = "雷光聚神茶", charge = true },
            { spellId = 115151, name = "复苏之雾", charge = true },
            { spellId = 115310, name = "还魂术" },
            { spellId = 116849, name = "作茧缚命" },
            { spellId = 115450, name = "清创生血" },
            { spellId = 443028, name = "天神御身" },
            { spellId = 322109, name = "轮回之触" },
            { spellId = 119381, name = "扫堂腿" },
            { spellId = 1270621, name = "宁神茶" },
            { spellId = 101643, name = "魂体双分" },
            { spellId = 119996, name = "魂体双分：转移" },
            { spellId = 107428, name = "旭日东升踢" },
            { spellId = 100784, name = "幻灭踢" },
            { spellId = 116844, name = "平心之环" },
            { spellId = 115078, name = "分筋错骨" },
            { spellId = 115294, name = "法力茶", castCount = 20 },
            { spellId = 399491, name = "神龙之赐", castCount = 10 },
        },
        group = {
            num = 5,
            healthPercent = 1,
            role = 2,
        },
    },
    [3] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "施法",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "敌人数量",
            },
            ["能量"] = {
                "能量值",
                "真气",
            },
            ["目标"] = {
                "类型",
                "生命值",
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["焦点"] = {
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
        },
        spells = {
            { spellId = 122470, name = "业报之触" },
            { spellId = 107428, name = "旭日东升踢" },
            { spellId = 1249625, name = "乾元之巅", charge = true, maxCharge = 2 },
            { spellId = 218164, name = "清创生血" },
            { spellId = 152175, name = "升龙霸" },
            { spellId = 101545, name = "翔龙在天" },
            { spellId = 113656, name = "怒雷破" },
            { spellId = 322109, name = "轮回之触" },
            { spellId = 119381, name = "扫堂腿" },
            { spellId = 322101, name = "移花接木" },
            { spellId = 101643, name = "魂体双分" },
            { spellId = 119996, name = "魂体双分：转移" },
            { spellId = 116705, name = "切喉手" },
            { spellId = 198898, name = "赤精之歌" },
            { spellId = 116844, name = "平心之环" },
            { spellId = 115078, name = "分筋错骨" },
        },
    },
}

Fuyutsui.spellsList = {
    [384255]  = { index = 151,  name = "切换天赋" },
    [200749]  = { index = 152,  name = "切换专精" },
    -- 种族（主动技能；同类技能多职业变体共用同一 index）
    [28730]   = { index = 101,  name = "奥术洪流" },
    [25046]   = { index = 101,  name = "奥术洪流" },
    [50613]   = { index = 101,  name = "奥术洪流" },
    [69179]   = { index = 101,  name = "奥术洪流" },
    [80483]   = { index = 101,  name = "奥术洪流" },
    [129597]  = { index = 101,  name = "奥术洪流" },
    [155145]  = { index = 101,  name = "奥术洪流" },
    [202719]  = { index = 101,  name = "奥术洪流" },
    [232633]  = { index = 101,  name = "奥术洪流" },
    [20594]   = { index = 102,  name = "石像形态" },
    [58984]   = { index = 103,  name = "影遁" },
    [26297]   = { index = 104,  name = "狂暴" },
    [20572]   = { index = 105,  name = "血性狂怒" },
    [33697]   = { index = 105,  name = "血性狂怒" },
    [33702]   = { index = 105,  name = "血性狂怒" },
    [20549]   = { index = 106,  name = "战争践踏" },
    [59752]   = { index = 107,  name = "生存意志" },
    [7744]    = { index = 108,  name = "亡灵意志" },
    [20589]   = { index = 109,  name = "逃命专家" },
    [68992]   = { index = 110,  name = "黑暗飞行" },
    [69070]   = { index = 111,  name = "火箭跳" },
    [69041]   = { index = 112,  name = "火箭弹幕" },
    [256948]  = { index = 113,  name = "空间裂隙" },
    [255647]  = { index = 114,  name = "圣光裁决" },
    [274738]  = { index = 115,  name = "先祖召唤" },
    [265221]  = { index = 116,  name = "烈焰之血" },
    [255654]  = { index = 117,  name = "蛮牛冲撞" },
    [255723]  = { index = 117,  name = "蛮牛冲撞" },
    [260364]  = { index = 118,  name = "奥术脉冲" },
    [312411]  = { index = 119,  name = "袋里乾坤" },
    [291944]  = { index = 120,  name = "再生" },
    [107079]  = { index = 121,  name = "震山掌" },
    [28880]   = { index = 122,  name = "纳鲁的赐福" },
    [59542]   = { index = 122,  name = "纳鲁的赐福" },
    [59543]   = { index = 122,  name = "纳鲁的赐福" },
    [59544]   = { index = 122,  name = "纳鲁的赐福" },
    [59545]   = { index = 122,  name = "纳鲁的赐福" },
    [59547]   = { index = 122,  name = "纳鲁的赐福" },
    [121093]  = { index = 122,  name = "纳鲁的赐福" },
    [287712]  = { index = 123,  name = "重拳出击" },
    [312924]  = { index = 124,  name = "超有机光发起源" },
    [368970]  = { index = 125,  name = "扫尾" },
    [357214]  = { index = 126,  name = "翼击" },
    [436344]  = { index = 127,  name = "艾泽里特涌动" },
    -- 武僧
    [322109]  = { index = 1,  name = "轮回之触" },
    [119381]  = { index = 2,  name = "扫堂腿" },
    [101643]  = { index = 3,  name = "魂体双分" },
    [119996]  = { index = 4,  name = "转移" },
    [115310]  = { index = 5,  name = "还魂术" },
    [116844]  = { index = 6,  name = "平心之环" },
    [115078]  = { index = 7,  name = "分筋错骨" },
    [132578]  = { index = 8,  name = "玄牛下凡" },
    [100780]  = { index = 9,  name = "猛虎掌" },
    [322729]  = { index = 10,  name = "神鹤引项踢" },
    [205523]  = { index = 11,  name = "幻灭踢" },
    [325153]  = { index = 12,  name = "爆炸酒桶" },
    [123986]  = { index = 13,  name = "真气爆裂" },
    [121253]  = { index = 14,  name = "醉酿投" },
    [115181]  = { index = 15,  name = "火焰之息" },
    [116847]  = { index = 16,  name = "碧玉疾风" },
    [117952]  = { index = 17,  name = "碎玉闪电" },
    [101546]  = { index = 18,  name = "神鹤引项踢" },
    [100784]  = { index = 19,  name = "幻灭踢" },
    [113656]  = { index = 20,  name = "怒雷破" },
    [107428]  = { index = 21,  name = "旭日东升踢" },
    [392983]  = { index = 22,  name = "风领主之击" },
    [467307]  = { index = 23,  name = "疾风呼啸踢" },
    [152175]  = { index = 24,  name = "升龙霸" },
    [399491]  = { index = 25,  name = "神龙之赐" },
    [116670]  = { index = 26,  name = "活血术" },
    [115175]  = { index = 27,  name = "抚慰之雾" },
    [443028]  = { index = 28,  name = "天神御身" },
    [124682]  = { index = 29,  name = "氤氲之雾" },
    [115294]  = { index = 30,  name = "法力茶" },
}
