if UnitClassBase("player") ~= "PALADIN" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "法力值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "神圣能量" },
        [22] = { type = "block", name = "施法技能" },
        [23] = { type = "block", name = "施法目标" },
        [24] = { type = "block", name = "目标距离" },
        [25] = { type = "aura", name = "神圣意志", auraName = "神圣意志", showKey = "remaining" },
        [26] = { type = "aura", name = "圣光灌注", auraName = "圣光灌注", showKey = "remaining" },
        [27] = { type = "aura", name = "灌注层数", auraName = "圣光灌注", showKey = "count" },
        [28] = { type = "aura", name = "神性层数", auraName = "神性之手", showKey = "count" },
        [29] = { type = "aura", name = "美德道标", auraName = "美德道标", showKey = "remaining" },
        [30] = { type = "block", name = "爆发开关" },
        [31] = { type = "spell", spellId = 115750, name = "盲目之光" },
        [32] = { type = "spell", spellId = 853, name = "制裁之锤" },
        [33] = { type = "spell", spellId = 642, name = "圣盾术" },
        [34] = { type = "spell", spellId = 6940, name = "牺牲祝福" },
        [35] = { type = "spell", spellId = 1044, name = "自由祝福" },
        [36] = { type = "spell", spellId = 1022, name = "保护祝福" },
        [37] = { type = "spell", spellId = 633, name = "圣疗术" },
        [38] = { type = "spell", spellId = 20473, name = "神圣震击" },
        [39] = { type = "spell", spellId = 20473, name = "神圣震击", charge = true, },
        [40] = { type = "spell", spellId = 4987, name = "清洁术" },
        [41] = { type = "spell", spellId = 275773, name = "审判" },
        [42] = { type = "spell", spellId = 375576, name = "圣洁鸣钟" },
        [43] = { type = "spell", spellId = 114165, name = "神圣棱镜" },
        [44] = { type = "spell", spellId = 31821, name = "光环掌握" },
        [45] = { type = "spell", spellId = 200025, name = "美德道标" },
        [46] = { type = "block", name = "大红冷却" },
        [47] = { type = "block", name = "延迟" },
        [48] = { type = "block", name = "目标施法" },
        [49] = { type = "block", name = "目标施法可打断" },

        [70] = {
            type = "group",
            num = 6,
            healthPercent = 1,
            role = 2,
        },
    },
    [2] = {
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "法力值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "神圣能量" },
        [22] = { type = "aura", name = "神圣意志", auraName = "神圣意志", showKey = "remaining" },
        [23] = { type = "aura", name = "神圣壁垒", auraName = "神圣壁垒", showKey = "remaining" },
        [24] = { type = "aura", name = "圣洁武器", auraName = "圣洁武器", showKey = "remaining" },
        [25] = { type = "aura", name = "闪耀之光", auraName = "闪耀之光", showKey = "remaining" },
        [26] = { type = "aura", name = "闪光层数", auraName = "闪耀之光", showKey = "count" },
        [27] = { type = "aura", name = "神圣军备", auraName = "神圣军备", showKey = "isIcon" },
        [28] = { type = "aura", name = "奉献", auraName = "奉献", showKey = "remaining" },
        [29] = { type = "aura", name = "复仇之怒", auraName = "复仇之怒", showKey = "remaining" },
        [30] = { type = "aura", name = "圣光之锤", auraName = "圣光之锤", showKey = "remaining" },
        [31] = { type = "block", name = "目标距离" },
        [32] = { type = "spell", spellId = 115750, name = "盲目之光" },
        [33] = { type = "spell", spellId = 853, name = "制裁之锤" },
        [34] = { type = "spell", spellId = 642, name = "圣盾术" },
        [35] = { type = "spell", spellId = 6940, name = "牺牲祝福" },
        [36] = { type = "spell", spellId = 1044, name = "自由祝福" },
        [37] = { type = "spell", spellId = 1022, name = "保护祝福" },
        [38] = { type = "spell", spellId = 633, name = "圣疗术" },
        [39] = { type = "spell", spellId = 432459, name = "神圣壁垒" },
        [40] = { type = "spell", spellId = 432459, name = "神圣壁垒", charge = true, },
        [41] = { type = "spell", spellId = 213644, name = "清毒术" },
        [42] = { type = "spell", spellId = 275779, name = "审判" },
        [43] = { type = "spell", spellId = 375576, name = "圣洁鸣钟" },
        [44] = { type = "spell", spellId = 31935, name = "复仇者之盾" },
        [45] = { type = "spell", spellId = 26573, name = "奉献" },
        [46] = { type = "spell", spellId = 53600, name = "正义盾击" },
        [47] = { type = "spell", spellId = 204019, name = "祝福之锤" },
        [48] = { type = "spell", spellId = 24275, name = "正义之锤" },
        [49] = { type = "block", name = "大红冷却" },
        [50] = { type = "block", name = "延迟" },
        [51] = { type = "block", name = "目标施法" },
        [52] = { type = "block", name = "目标施法可打断" },
        [53] = { type = "block", name = "焦点施法" },
        [54] = { type = "block", name = "焦点施法可打断" },
        [55] = { type = "block", name = "目标引导" },
        [56] = { type = "block", name = "目标引导可打断" },
        [57] = { type = "block", name = "焦点引导" },
        [58] = { type = "block", name = "焦点引导可打断" },
        [70] = {
            type = "group",
            num = 3,
            healthPercent = 1,
            role = 2,
        },
    },
    [3] = {
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "法力值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "神圣能量" },
        [22] = { type = "block", name = "爆发开关" },
        [23] = { type = "block", name = "AOE开关" },
        [24] = { type = "block", name = "输出模式" },
        [25] = { type = "aura", name = "神圣意志", auraName = "神圣意志", showKey = "remaining" },
        [26] = { type = "aura", name = "复仇之怒", auraName = "复仇之怒", showKey = "remaining" },
        [27] = { type = "aura", name = "处决宣判", auraName = "处决宣判", showKey = "remaining" },
        [28] = { type = "aura", name = "圣光之锤", auraName = "圣光之锤", showKey = "remaining" },
        [29] = { type = "block", name = "敌人人数" },
        [30] = { type = "block", name = "目标距离" },
        [31] = { type = "spell", spellId = 115750, name = "盲目之光" },
        [32] = { type = "spell", spellId = 853, name = "制裁之锤" },
        [33] = { type = "spell", spellId = 642, name = "圣盾术" },
        [34] = { type = "spell", spellId = 6940, name = "牺牲祝福" },
        [35] = { type = "spell", spellId = 1044, name = "自由祝福" },
        [36] = { type = "spell", spellId = 1022, name = "保护祝福" },
        [37] = { type = "spell", spellId = 633, name = "圣疗术" },
        [38] = { type = "spell", spellId = 213644, name = "清毒术" },
        [39] = { type = "spell", spellId = 20271, name = "审判" },
        [40] = { type = "spell", spellId = 20271, name = "审判", charge = true, },
        [41] = { type = "spell", spellId = 375576, name = "圣洁鸣钟" },
        [42] = { type = "spell", spellId = 184575, name = "公正之剑" },
        [43] = { type = "spell", spellId = 343527, name = "处决宣判" },
        [44] = { type = "spell", spellId = 255937, name = "灰烬觉醒" },
        [45] = { type = "spell", spellId = 31884, name = "复仇之怒" },
        [46] = { type = "block", name = "大红冷却" },
        [47] = { type = "block", name = "延迟" },
        [48] = { type = "block", name = "目标施法" },
        [49] = { type = "block", name = "目标施法可打断" },
        [50] = { type = "block", name = "焦点施法" },
        [51] = { type = "block", name = "焦点施法可打断" },
        [52] = { type = "block", name = "目标引导" },
        [53] = { type = "block", name = "目标引导可打断" },
        [54] = { type = "block", name = "焦点引导" },
        [55] = { type = "block", name = "焦点引导可打断" },
        [70] = {
            type = "group",
            num = 3,
            healthPercent = 1,
            role = 2,
        },
    },
} -- 创建圣骑士宏{
Fuyutsui.MacrosList = {
    dynamicSpells = { "神圣震击", "圣光闪现", "圣光术", "荣耀圣令", "清毒术", "圣疗术" },
    specialSpells = {},
    staticSpells = {
        [1] = "牺牲祝福",
        [2] = "代祷",
        [3] = "圣盾术",
        [4] = "盲目之光",
        [5] = "[@mouseover]保护祝福",
        [6] = "审判",
        [7] = "制裁之锤",
        [8] = "光环掌握",
        [9] = "圣洁鸣钟",
        [10] = "正义盾击",
        [11] = "黎明之光",
        [12] = "[target=mouseover,help][@player]自由祝福",
        [13] = "神圣棱镜",
        [14] = "神圣震击",
        [15] = "公正之剑",
        [16] = "[@player]圣洁鸣钟",
        [17] = "处决宣判",
        [18] = "最终审判",
        [19] = "复仇之怒",
        [20] = "[spec:2]圣洁鸣钟;[spec:3]灰烬觉醒",
        [21] = "复仇者之盾",
        [22] = "责难",
        [23] = "远古列王守卫",
        [24] = "十字军打击",
        [25] = "炽热防御者",
        [26] = "[@mouseover]破咒祝福",
        [27] = "神圣风暴",
        [28] = "奉献",
        [29] = "神圣壁垒",
        [30] = "[@player]荣耀圣令",
        [31] = "圣光道标",
        [32] = "银月城生命药水",
        [33] = "清毒术",
    },
}
