if UnitClassBase("player") ~= "PRIEST" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "施法",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "施法技能",
                "施法目标",
                "敌人数量",
            },
            ["能量"] = {
                "法力值",
            },
            ["物品"] = {
                "魔法药水",
                "治疗药水",
                "治疗石",
                "鲁莽药水",
            },
            ["配置开关"] = {
                "延迟",
            },
            ["目标"] = {
                "类型",
                "生命值",
                "施法",
                "施法可打断",
            },
        },
        auras = {
            player = {
                { name = "熵能裂隙", spellId = 450193, },
                { name = "天使长", spellId = 81700, },
                { name = "阴暗面之力", spellId = 198069 },
                { name = "黑暗主宰", spellId = 1253591, maxApps = 2, },
                { name = "圣光涌动", spellId = 114255, maxApps = 2, },
                { name = "福音", spellId = 472433, maxApps = 2, },
                { name = "强效惩击", spellId = 1253725, maxApps = 2 },
                { name = "严酷戒律", spellId = 373183, maxApps = 2 },
                { name = "祸福相依", spellId = 390787, maxApps = 10, },
            },
            target = {
                harmful = {
                    { name = "暗言术：痛", spellId = 589, },
                },
                helpful = {
                    { name = "救赎", spellId = 194384, },
                    { name = "真言术：盾", spellIds = { 17, 1253593 }, },
                },
            },
            focus = {
                harmful = {
                    { name = "暗言术：痛", spellId = 589, },
                },
                helpful = {
                    { name = "救赎", spellId = 194384, },
                    { name = "真言术：盾", spellIds = { 17, 1253593 }, },
                },
            },
        },
        spells = {
            { spellId = 8122, name = "心灵尖啸" },
            { spellId = 32375, name = "群体驱散" },
            { spellId = 527, name = "纯净术" },
            { spellId = 19236, name = "绝望祷言" },
            { spellId = 232633, name = "奥术洪流" },
            { spellId = 47540, name = "苦修", charge = true, maxCharge = 2 },
            { spellId = 194509, name = "真言术：耀", charge = true, maxCharge = 2 },
            { spellId = 17, name = "真言术：盾" },
            { spellId = 62618, name = "真言术：障" },
            { spellId = 421453, name = "终极苦修" },
            { spellId = 472433, name = "福音" },
            { spellId = 8092, name = "心灵震爆" },
            { spellId = 32379, name = "暗言术：灭" },
            { spellId = 34433, name = "暗影魔" },
            { spellId = 1235211, name = "暗影分流" },
            { spellId = 586, name = "渐隐术" },
        },
        group = {
            num = 5,
            healthPercent = 1,
            role = 2,
            dispel = 3,
            aura = {
                [4] = { name = "救赎", spellId = 194384, },
                [5] = { name = "真言术：盾", spellIds = { 17, 1253593 }, },
            },
        },
    },
    [2] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "施法",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "施法技能",
                "施法目标",
                "救赎之魂1",
                "救赎之魂2",
            },
            ["能量"] = {
                "法力值",
            },
            ["目标"] = {
                "类型",
                "施法",
                "施法可打断",
            },
        },
        auras = {
            player = {
                { name = "神圣化身", spellId = 200183, },
                { name = "神圣镜像", spellId = 405216, },
                { name = "圣光涌动", spellId = 114255, maxApps = 2, },
                { name = "祈福", spellId = 1262766, },
                { name = "救赎之魂", spellId = 194384, },
            },
            target = {
                harmful = {
                    { name = "暗言术：痛", spellId = 589, },
                    { name = "神圣之火", spellId = 14914, },
                },
                helpful = {
                    { name = "愈合祷言", spellId = 41635, },
                    { name = "恢复", spellIds = 139, },
                },
            },
            focus = {
                harmful = {
                    { name = "暗言术：痛", spellId = 589, },
                    { name = "神圣之火", spellId = 14914, },
                },
                helpful = {
                    { name = "愈合祷言", spellId = 41635, },
                    { name = "恢复", spellIds = 139, },
                },
            },
        },
        spells = {
            { spellId = 8122, name = "心灵尖啸" },
            { spellId = 32375, name = "群体驱散" },
            { spellId = 527, name = "纯净术" },
            { spellId = 19236, name = "绝望祷言" },
            { spellId = 232633, name = "奥术洪流" },
            { spellId = 33076, name = "愈合祷言", charge = true, maxCharge = 2 },
            { spellId = 2050, name = "圣言术：静", charge = true, maxCharge = 2 },
            { spellId = 88625, name = "圣言术：罚" },
            { spellId = 200183, name = "神圣化身" },
            { spellId = 14914, name = "神圣之火" },
            { spellId = 120517, name = "光晕" },
            { spellId = 64843, name = "神圣赞美诗" },
        },
        group = {
            num = 5,
            healthPercent = 1,
            role = 2,
            dispel = 3,
            aura = {
                [4] = { name = "恢复", spellId = 139, },
                [5] = { name = "愈合祷言", spellId = 41635, },
            },
        },
    },
    [3] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "施法",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "敌人数量",
                "施法技能",
                "姿态",
            },
            ["能量"] = {
                "狂乱值",
                "法力值",
            },
            ["配置开关"] = {
                "爆发开关",
                "输出模式",
                "AOE开关",
            },
            ["目标"] = {
                "类型",
                "距离",
                "生命值",
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["焦点"] = {
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
        },
        auras = {
            player = {
                { name = "虚空齐射", spellId = 1242171, maxApps = 5, },
                { name = "命运多舛", spellId = 390978 },
                { name = "熵能裂隙", spellId = 450193, },
                { name = "暗影洞察", spellId = 375981, },
                { name = "尤格-萨隆的神像", spellId = 373276, maxApps = 20, },
            },
            target = {
                harmful = {
                    { name = "暗言术：痛", spellId = 589, },
                    { name = "吸血鬼之触", spellId = 34914, },
                    { name = "暗言术：癫", spellId = 335467, },
                    { name = "精神鞭笞", spellId = 15407, },
                    { name = "惊魂幻象", spellId = 1243069, maxApps = 100, },
                },
                helpful = {
                    { name = "愈合祷言", spellId = 41635, },
                    { name = "恢复", spellIds = 139, },
                },
            },
            focus = {
                harmful = {
                    { name = "暗言术：痛", spellId = 589, },
                    { name = "神圣之火", spellId = 14914, },
                },
                helpful = {
                    { name = "愈合祷言", spellId = 41635, },
                    { name = "恢复", spellIds = 139, },
                },
            },
        },
        spells = {
            { spellId = 8122, name = "心灵尖啸" },
            { spellId = 32375, name = "群体驱散" },
            { spellId = 527, name = "纯净术" },
            { spellId = 19236, name = "绝望祷言" },
            { spellId = 232633, name = "奥术洪流" },
            { spellId = 8092, name = "心灵震爆" },
            { spellId = 32379, name = "暗言术：灭" },
            { spellId = 263165, name = "虚空洪流" },
            { spellId = 228260, name = "虚空形态" },
            { spellId = 1227280, name = "触须猛击" },
            { spellId = 15286, name = "吸血鬼的拥抱" },
            { spellId = 120644, name = "光晕" },
            { spellId = 1242173, name = "虚空齐射" },
        },
    },
}

Fuyutsui.spellsList = {
    [384255]  = { index = 151, name = "切换天赋" },
    [200749]  = { index = 152, name = "切换专精" },
    -- 种族（主动技能；同类技能多职业变体共用同一 index）
    [28730]   = { index = 101, name = "奥术洪流" },
    [25046]   = { index = 101, name = "奥术洪流" },
    [50613]   = { index = 101, name = "奥术洪流" },
    [69179]   = { index = 101, name = "奥术洪流" },
    [80483]   = { index = 101, name = "奥术洪流" },
    [129597]  = { index = 101, name = "奥术洪流" },
    [155145]  = { index = 101, name = "奥术洪流" },
    [202719]  = { index = 101, name = "奥术洪流" },
    [232633]  = { index = 101, name = "奥术洪流" },
    [20594]   = { index = 102, name = "石像形态" },
    [58984]   = { index = 103, name = "影遁" },
    [26297]   = { index = 104, name = "狂暴" },
    [20572]   = { index = 105, name = "血性狂怒" },
    [33697]   = { index = 105, name = "血性狂怒" },
    [33702]   = { index = 105, name = "血性狂怒" },
    [20549]   = { index = 106, name = "战争践踏" },
    [59752]   = { index = 107, name = "生存意志" },
    [7744]    = { index = 108, name = "亡灵意志" },
    [20589]   = { index = 109, name = "逃命专家" },
    [68992]   = { index = 110, name = "黑暗飞行" },
    [69070]   = { index = 111, name = "火箭跳" },
    [69041]   = { index = 112, name = "火箭弹幕" },
    [256948]  = { index = 113, name = "空间裂隙" },
    [255647]  = { index = 114, name = "圣光裁决" },
    [274738]  = { index = 115, name = "先祖召唤" },
    [265221]  = { index = 116, name = "烈焰之血" },
    [255654]  = { index = 117, name = "蛮牛冲撞" },
    [255723]  = { index = 117, name = "蛮牛冲撞" },
    [260364]  = { index = 118, name = "奥术脉冲" },
    [312411]  = { index = 119, name = "袋里乾坤" },
    [291944]  = { index = 120, name = "再生" },
    [107079]  = { index = 121, name = "震山掌" },
    [28880]   = { index = 122, name = "纳鲁的赐福" },
    [59542]   = { index = 122, name = "纳鲁的赐福" },
    [59543]   = { index = 122, name = "纳鲁的赐福" },
    [59544]   = { index = 122, name = "纳鲁的赐福" },
    [59545]   = { index = 122, name = "纳鲁的赐福" },
    [59547]   = { index = 122, name = "纳鲁的赐福" },
    [121093]  = { index = 122, name = "纳鲁的赐福" },
    [287712]  = { index = 123, name = "重拳出击" },
    [312924]  = { index = 124, name = "超有机光发起源" },
    [368970]  = { index = 125, name = "扫尾" },
    [357214]  = { index = 126, name = "翼击" },
    [436344]  = { index = 127, name = "艾泽里特涌动" },

    [8122]    = { index = 1, name = "心灵尖啸" },
    [32375]   = { index = 2, name = "群体驱散" },
    [62618]   = { index = 3, name = "真言术：障" },
    [421453]  = { index = 4, name = "终极苦修" },
    [200183]  = { index = 5, name = "神圣化身" },
    [120517]  = { index = 6, name = "光晕" },
    [64843]   = { index = 7, name = "神圣赞美诗" },
    [228260]  = { index = 8, name = "虚空形态" },
    [15286]   = { index = 9, name = "吸血鬼的拥抱" },
    [21562]   = { index = 10, name = "真言术：韧" },
    [8092]    = { index = 11, name = "心灵震爆" },
    [585]     = { index = 12, name = "惩击" },
    [32379]   = { index = 13, name = "暗言术：灭" },
    [589]     = { index = 14, name = "暗言术：痛" },
    [47540]   = { index = 15, name = "苦修" },
    [47757]   = { index = 15, name = "苦修" },
    [47758]   = { index = 15, name = "苦修" },
    [88625]   = { index = 16, name = "圣言术：罚" },
    [14914]   = { index = 17, name = "神圣之火" },
    [132157]  = { index = 18, name = "神圣新星" },
    [34914]   = { index = 19, name = "吸血鬼之触" },
    [232698]  = { index = 20, name = "暗影形态" },
    [335467]  = { index = 21, name = "暗言术：癫" },
    [15407]   = { index = 22, name = "精神鞭笞" },
    [263165]  = { index = 23, name = "虚空洪流" },
    [1227280] = { index = 24, name = "触须猛击" },
    [450983]  = { index = 25, name = "虚空冲击" },
    [1242173] = { index = 26, name = "虚空齐射" },
    [391403]  = { index = 27, name = "精神鞭笞：狂" },
    [120644]  = { index = 28, name = "光晕" },
    [2061]    = { index = 29, name = "快速治疗" },
    [194509]  = { index = 30, name = "真言术：耀" },
    [64863]   = { index = 31, name = "神圣赞美诗" },
    [596]     = { index = 32, name = "治疗祷言" },
    [1262763] = { index = 33, name = "祈福" },
    [186263]  = { index = 34, name = "暗影愈合" },
    [472433]  = { index = 35, name = "福音" },
}
