if UnitClassBase("player") ~= "SHAMAN" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "漩涡值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "目标生命值" },
        [22] = { type = "block", name = "敌人人数" },
        [23] = { type = "block", name = "目标施法" },
        [24] = { type = "block", name = "目标施法可打断" },
        [25] = { type = "block", name = "焦点施法" },
        [26] = { type = "block", name = "焦点施法可打断" },
        [27] = { type = "block", name = "目标引导" },
        [28] = { type = "block", name = "目标引导可打断" },
        [29] = { type = "block", name = "焦点引导" },
        [30] = { type = "block", name = "焦点引导可打断" },
        [31] = { type = "spell", spellId = 57994, name = "风剪" },
        [32] = { type = "spell", spellId = 198103, name = "土元素" },
        [33] = { type = "spell", spellId = 192058, name = "电能图腾" },
        [34] = { type = "spell", spellId = 378081, name = "自然迅捷" },
        [35] = { type = "spell", spellId = 108287, name = "图腾投射" },
        [36] = { type = "spell", spellId = 51514, name = "妖术" },
        [37] = { type = "spell", spellId = 378773, name = "强化净化术" },
        [38] = { type = "spell", spellId = 8143, name = "战栗图腾" },
        [39] = { type = "spell", spellId = 383013, name = "清毒图腾" },
        [40] = { type = "spell", spellId = 192063, name = "阵风" },
        [41] = { type = "spell", spellId = 58875, name = "幽魂步" },

        [42] = { type = "block", name = "大红冷却" },
    },
    [2] = {
        ["countBars"] = {
            { valueType = "castCount", name = "溢流漩涡", minValue = 0, maxValue = 20, spellId = 8004 },
        },
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "法力值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "目标生命值" },
        [22] = { type = "block", name = "敌人人数" },
        [23] = { type = "block", name = "目标施法" },
        [24] = { type = "block", name = "目标施法可打断" },
        [25] = { type = "block", name = "焦点施法" },
        [26] = { type = "block", name = "焦点施法可打断" },
        [27] = { type = "block", name = "目标引导" },
        [28] = { type = "block", name = "目标引导可打断" },
        [29] = { type = "block", name = "焦点引导" },
        [30] = { type = "block", name = "焦点引导可打断" },
        [31] = { type = "spell", spellId = 57994, name = "风剪" },
        [32] = { type = "spell", spellId = 198103, name = "土元素" },
        [33] = { type = "spell", spellId = 192058, name = "电能图腾" },
        [34] = { type = "spell", spellId = 378081, name = "自然迅捷" },
        [35] = { type = "spell", spellId = 108287, name = "图腾投射" },
        [36] = { type = "spell", spellId = 51514, name = "妖术" },
        [37] = { type = "spell", spellId = 378773, name = "强化净化术" },
        [38] = { type = "spell", spellId = 8143, name = "战栗图腾" },
        [39] = { type = "spell", spellId = 383013, name = "清毒图腾" },
        [40] = { type = "spell", spellId = 192063, name = "阵风" },
        [41] = { type = "spell", spellId = 58875, name = "幽魂步" },
        [42] = { type = "block", name = "漩涡武器层数" },
        [43] = { type = "spell", spellId = 187874, name = "毁灭闪电" },
        [44] = { type = "spell", spellId = 60103, name = "熔岩猛击" },
        [45] = { type = "spell", spellId = 17364, name = "风暴打击" },
        [46] = { type = "spell", spellId = 470057, name = "流电炽焰" },
        [47] = { type = "spell", spellId = 196884, name = "狂野扑击" },
        [48] = { type = "spell", spellId = 108271, name = "星界转移" },
        [49] = { type = "block", name = "爆发开关" },
        [50] = { type = "block", name = "输出模式" },
        [51] = { type = "block", name = "AOE开关" },
        [52] = { type = "block", name = "爆发药水开关" },
        [53] = { type = "block", name = "目标距离" },
        [54] = { type = "block", name = "延迟" },
    },
    [3] = {
        ["countBars"] = {
            { valueType = "charge", name = "激流", minValue = 0, maxValue = 2, spellId = 61295 },
            { valueType = "charge", name = "治疗之泉图腾", minValue = 0, maxValue = 4, spellId = 5394 }
        },
        [9] = { type = "block", name = "战斗时间" },
        [10] = { type = "block", name = "移动" },
        [11] = { type = "block", name = "施法" },
        [12] = { type = "block", name = "引导" },
        [13] = { type = "block", name = "蓄力" },
        [14] = { type = "block", name = "蓄力层数" },
        [15] = { type = "block", name = "生命值" },
        [16] = { type = "block", name = "法力值" },
        [17] = { type = "block", name = "目标类型" },
        [18] = { type = "block", name = "队伍人数" },
        [19] = { type = "block", name = "首领战" },
        [20] = { type = "block", name = "难度" },
        [21] = { type = "block", name = "延迟" },
        [22] = { type = "block", name = "施法技能" },
        [23] = { type = "block", name = "施法目标" },
        [58] = { type = "block", name = "目标施法" },
        [59] = { type = "block", name = "目标施法可打断" },
        [60] = { type = "block", name = "焦点施法" },
        [61] = { type = "block", name = "焦点施法可打断" },
        [62] = { type = "block", name = "目标引导" },
        [63] = { type = "block", name = "目标引导可打断" },
        [64] = { type = "block", name = "焦点引导" },
        [65] = { type = "block", name = "焦点引导可打断" },
        [24] = { type = "aura", name = "飞旋之土", auraName = "飞旋之土", showKey = "remaining" },
        [25] = { type = "aura", name = "潮汐奔涌", auraName = "潮汐奔涌", showKey = "remaining" },
        [26] = { type = "aura", name = "风暴涌流图腾", auraName = "风暴涌流图腾", showKey = "remaining" },
        [27] = { type = "aura", name = "风暴涌流图腾层数", auraName = "风暴涌流图腾", showKey = "count" },
        [28] = { type = "aura", name = "生命释放", auraName = "生命释放", showKey = "remaining" },
        [29] = { type = "aura", name = "升腾", auraName = "升腾", showKey = "remaining" },
        [30] = { type = "aura", name = "风暴涌流图腾-持续时间", auraName = "风暴涌流图腾-持续时间", showKey = "remaining" },
        [56] = { type = "aura", name = "倾盆大雨", auraName = "倾盆大雨", showKey = "remaining" },
        [57] = { type = "aura", name = "倾盆大雨层数", auraName = "倾盆大雨", showKey = "count" },
        [31] = { type = "spell", spellId = 57994, name = "风剪" },
        [32] = { type = "spell", spellId = 198103, name = "土元素" },
        [33] = { type = "spell", spellId = 192058, name = "电能图腾" },
        [34] = { type = "spell", spellId = 378081, name = "自然迅捷" },
        [35] = { type = "spell", spellId = 108287, name = "图腾投射" },
        [36] = { type = "spell", spellId = 51514, name = "妖术" },
        [37] = { type = "spell", spellId = 378773, name = "强化净化术" },
        [38] = { type = "spell", spellId = 8143, name = "战栗图腾" },
        [39] = { type = "spell", spellId = 383013, name = "清毒图腾" },
        [40] = { type = "spell", spellId = 192063, name = "阵风" },
        [41] = { type = "spell", spellId = 58875, name = "幽魂步" },
        [42] = { type = "spell", spellId = 51505, name = "熔岩爆裂" },
        [43] = { type = "spell", spellId = 51505, name = "熔岩爆裂", charge = true },
        [44] = { type = "spell", spellId = 61295, name = "激流" },
        [45] = { type = "spell", spellId = 61295, name = "激流", charge = true },
        [46] = { type = "spell", spellId = 5394, name = "治疗之泉图腾" },
        [47] = { type = "spell", spellId = 5394, name = "治疗之泉图腾", charge = true },
        [48] = { type = "spell", spellId = 470411, name = "烈焰震击" },
        [49] = { type = "spell", spellId = 77130, name = "净化灵魂" },
        [50] = { type = "spell", spellId = 73685, name = "生命释放" },
        [51] = { type = "spell", spellId = 443454, name = "先祖迅捷" },
        [52] = { type = "spell", spellId = 444995, name = "涌动图腾", inSpellBook = true },
        [53] = { type = "spell", spellId = 98008, name = "灵魂链接图腾" },
        [54] = { type = "spell", spellId = 114052, name = "升腾" },
        [55] = { type = "spell", spellId = 108280, name = "治疗之潮图腾" },
        [256] = {
            type = "group",
            num = 6,
            healthPercent = 1,
            role = 2,
            dispel = 3,
            auras = {
                [4] = { 61295 },       -- 激流
                [5] = { 974, 383648 }, -- 大地之盾
                [6] = { 382024 },      -- 大地生命武器
            },
        },
    },
}
Fuyutsui.MacrosList = {
    dynamicSpells = { "治疗波", "治疗链", "激流", "大地之盾", "净化灵魂", "生命释放" },
    specialSpells = {},
    staticSpells = {
        [1] = "唤潮者的护卫",
        [2] = "大地生命武器",
        [3] = "天怒",
        [4] = "水之护盾",
        [5] = "烈焰震击",
        [6] = "熔岩爆裂",
        [7] = "闪电箭",
        [8] = "闪电链",
        [9] = "治疗之泉图腾",
        [10] = "风剪",
        [11] = "先祖迅捷",
        [12] = "自然迅捷",
        [13] = "[@cursor]治疗之雨",
        [14] = "[@cursor]电能图腾",
        [15] = "阵风",
        [16] = "[@cursor]灵魂链接图腾",
        [17] = "土元素",
        [18] = "战栗图腾",
        [19] = "清毒图腾",
        [20] = "图腾投射",
        [21] = "升腾",
        [22] = "治疗之潮图腾",
        [23] = "毁灭闪电",
        [24] = "流电炽焰",
        [25] = "火舌武器",
        [26] = "熔岩猛击",
        [27] = "裂地术",
        [28] = "始源风暴",
        [29] = "风切",
        [30] = "风怒武器",
        [31] = "风暴打击",
        [32] = "狂风怒号",
        [33] = "元素冲击",
        [34] = "地震术",
        [35] = "大地震击",
        [36] = "风暴守护者",
        [37] = "闪电之盾",
        [38] = "[@cursor]治疗之雨",
        [39] = "[@cursor]狂风图腾",
        [40] = "[@target]净化灵魂",
        [41] = "[@focus]风剪",
    },
}
