if UnitClassBase("player") ~= "SHAMAN" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "施法",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "敌人数量",
            },
            ["能量"] = {
                "漩涡值",
            },
            ["物品"] = {
                "治疗药水",
            },
            ["目标"] = {
                "类型",
                "生命值",
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["焦点"] = {
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
        },
        spells = {
            { spellId = 57994, name = "风剪" },
            { spellId = 198103, name = "土元素" },
            { spellId = 192058, name = "电能图腾" },
            { spellId = 378081, name = "自然迅捷" },
            { spellId = 108287, name = "图腾投射" },
            { spellId = 51514, name = "妖术" },
            { spellId = 378773, name = "强化净化术" },
            { spellId = 8143, name = "战栗图腾" },
            { spellId = 383013, name = "清毒图腾" },
            { spellId = 192063, name = "阵风" },
            { spellId = 58875, name = "幽魂步" },
            { spellId = 73920, name = "治疗之雨" },
        },
    },
    [2] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "施法",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "敌人数量",
            },
            ["能量"] = {
                "法力值",
            },
            ["配置开关"] = {
                "爆发开关",
                "输出模式",
                "AOE开关",
                "爆发药水开关",
                "延迟",
            },
            ["目标"] = {
                "类型",
                "生命值",
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
                "距离",
            },
            ["焦点"] = {
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
        },
        spells = {
            { spellId = 57994, name = "风剪" },
            { spellId = 198103, name = "土元素" },
            { spellId = 192058, name = "电能图腾" },
            { spellId = 378081, name = "自然迅捷" },
            { spellId = 108287, name = "图腾投射" },
            { spellId = 51514, name = "妖术" },
            { spellId = 378773, name = "强化净化术" },
            { spellId = 8143, name = "战栗图腾" },
            { spellId = 383013, name = "清毒图腾" },
            { spellId = 192063, name = "阵风" },
            { spellId = 58875, name = "幽魂步" },
            { spellId = 187874, name = "毁灭闪电" },
            { spellId = 60103, name = "熔岩猛击" },
            { spellId = 17364, name = "风暴打击" },
            { spellId = 470057, name = "流电炽焰" },
            { spellId = 196884, name = "狂野扑击" },
            { spellId = 108271, name = "星界转移" },
            { spellId = 8004, name = "溢流漩涡", castCount = 20 },
        },
    },
    [3] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "施法",
                "引导",
                "蓄力",
                "蓄力层数",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "施法技能",
                "施法目标",
                "敌人数量",
                "敌人数-无仇恨",
                "敌人数-有仇恨",
            },
            ["能量"] = {
                "法力值",
            },
            ["配置开关"] = {
                "延迟",
            },
            ["目标"] = {
                "类型",
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["焦点"] = {
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
        },
        auras = {
            player = {
                { name = "大地之盾", spellId = 383648, },
                { name = "水之护盾", spellId = 52127, },
                { name = "治疗之雨", spellId = 1307888, },
                { name = "飞旋之土", spellId = 453406, },
                { name = "飞旋之水", spellId = 453407, },
                { name = "飞旋之风", spellId = 453409, },
                { name = "潮汐奔涌", spellId = 53390, maxApps = 2, },
                { name = "激流", spellId = 61295, },
                { name = "聚合水流", spellId = 470077, },
                { name = "升腾", spellId = 114052, },
                { name = "生命释放", spellId = 73685, },
                { name = "风暴涌流图腾", spellId = 1267089, maxApps = 2, },
                { name = "倾盆大雨", spellId = 462603, },
                { name = "自然迅捷", spellId = 378081, },
            },
        },
        spells = {
            { spellId = 57994, name = "风剪" },
            { spellId = 198103, name = "土元素" },
            { spellId = 192058, name = "电能图腾" },
            { spellId = 378081, name = "自然迅捷" },
            { spellId = 108287, name = "图腾投射" },
            { spellId = 51514, name = "妖术" },
            { spellId = 378773, name = "强化净化术" },
            { spellId = 8143, name = "战栗图腾" },
            { spellId = 383013, name = "清毒图腾" },
            { spellId = 192063, name = "阵风" },
            { spellId = 58875, name = "幽魂步" },
            { spellId = 51505, name = "熔岩爆裂", charge = true },
            { spellId = 61295, name = "激流", charge = true, maxCharge = 2 },
            { spellId = 5394, name = "治疗之泉图腾", charge = true, maxCharge = 4 },
            { spellId = 470411, name = "烈焰震击" },
            { spellId = 77130, name = "净化灵魂" },
            { spellId = 73685, name = "生命释放" },
            { spellId = 443454, name = "先祖迅捷" },
            { spellId = 444995, name = "涌动图腾"  },
            { spellId = 98008, name = "灵魂链接图腾" },
            { spellId = 114052, name = "升腾" },
            { spellId = 108280, name = "治疗之潮图腾" },
            { spellId = 73920, name = "治疗之雨" },
        },
        group = {
            num = 6,
            healthPercent = 1,
            role = 2,
            dispel = 3,
            aura = {
                [4] = { name = "激流", spellId = 61295, },
                [5] = { name = "大地之盾", spellIds = { 974, 383648 }, },
            },
        },
    },
}

Fuyutsui.spellsList = {
    [384255]  = { index = 151, name = "切换天赋" },
    [200749]  = { index = 152, name = "切换专精" },
    -- 种族（主动技能；同类技能多职业变体共用同一 index）
    [28730]   = { index = 101, name = "奥术洪流" },
    [25046]   = { index = 101, name = "奥术洪流" },
    [50613]   = { index = 101, name = "奥术洪流" },
    [69179]   = { index = 101, name = "奥术洪流" },
    [80483]   = { index = 101, name = "奥术洪流" },
    [129597]  = { index = 101, name = "奥术洪流" },
    [155145]  = { index = 101, name = "奥术洪流" },
    [202719]  = { index = 101, name = "奥术洪流" },
    [232633]  = { index = 101, name = "奥术洪流" },
    [20594]   = { index = 102, name = "石像形态" },
    [58984]   = { index = 103, name = "影遁" },
    [26297]   = { index = 104, name = "狂暴" },
    [20572]   = { index = 105, name = "血性狂怒" },
    [33697]   = { index = 105, name = "血性狂怒" },
    [33702]   = { index = 105, name = "血性狂怒" },
    [20549]   = { index = 106, name = "战争践踏" },
    [59752]   = { index = 107, name = "生存意志" },
    [7744]    = { index = 108, name = "亡灵意志" },
    [20589]   = { index = 109, name = "逃命专家" },
    [68992]   = { index = 110, name = "黑暗飞行" },
    [69070]   = { index = 111, name = "火箭跳" },
    [69041]   = { index = 112, name = "火箭弹幕" },
    [256948]  = { index = 113, name = "空间裂隙" },
    [255647]  = { index = 114, name = "圣光裁决" },
    [274738]  = { index = 115, name = "先祖召唤" },
    [265221]  = { index = 116, name = "烈焰之血" },
    [255654]  = { index = 117, name = "蛮牛冲撞" },
    [255723]  = { index = 117, name = "蛮牛冲撞" },
    [260364]  = { index = 118, name = "奥术脉冲" },
    [312411]  = { index = 119, name = "袋里乾坤" },
    [291944]  = { index = 120, name = "再生" },
    [107079]  = { index = 121, name = "震山掌" },
    [28880]   = { index = 122, name = "纳鲁的赐福" },
    [59542]   = { index = 122, name = "纳鲁的赐福" },
    [59543]   = { index = 122, name = "纳鲁的赐福" },
    [59544]   = { index = 122, name = "纳鲁的赐福" },
    [59545]   = { index = 122, name = "纳鲁的赐福" },
    [59547]   = { index = 122, name = "纳鲁的赐福" },
    [121093]  = { index = 122, name = "纳鲁的赐福" },
    [287712]  = { index = 123, name = "重拳出击" },
    [312924]  = { index = 124, name = "超有机光发起源" },
    [368970]  = { index = 125, name = "扫尾" },
    [357214]  = { index = 126, name = "翼击" },
    [436344]  = { index = 127, name = "艾泽里特涌动" },
    -- 萨满
    [457481]  = { index = 1, name = "唤潮者的护卫" },
    [382021]  = { index = 2, name = "大地生命武器" },
    [462854]  = { index = 3, name = "天怒" },
    [52127]   = { index = 4, name = "水之护盾" },
    [470411]  = { index = 5, name = "烈焰震击" },
    [51505]   = { index = 6, name = "熔岩爆裂" },
    [188196]  = { index = 7, name = "闪电箭" },
    [188443]  = { index = 8, name = "闪电链" },
    [5394]    = { index = 9, name = "治疗之泉图腾" },
    [57994]   = { index = 10, name = "风剪" },
    [443454]  = { index = 11, name = "先祖迅捷" },
    [378081]  = { index = 12, name = "自然迅捷" },
    [444995]  = { index = 13, name = "涌动图腾" },
    [192058]  = { index = 14, name = "电能图腾" },
    [192063]  = { index = 15, name = "阵风" },
    [98008]   = { index = 16, name = "灵魂链接图腾" },
    [198103]  = { index = 17, name = "土元素" },
    [8143]    = { index = 18, name = "战栗图腾" },
    [383013]  = { index = 19, name = "清毒图腾" },
    [108287]  = { index = 20, name = "图腾投射" },
    [114052]  = { index = 21, name = "升腾" },
    [108280]  = { index = 22, name = "治疗之潮图腾" },
    [187874]  = { index = 23, name = "毁灭闪电" },
    [470057]  = { index = 24, name = "流电炽焰" },
    [318038]  = { index = 25, name = "火舌武器" },
    [60103]   = { index = 26, name = "熔岩猛击" },
    [197214]  = { index = 27, name = "裂地术" },
    [1218090] = { index = 28, name = "始源风暴" },
    [115356]  = { index = 29, name = "风切" },
    [33757]   = { index = 30, name = "风怒武器" },
    [17364]   = { index = 31, name = "风暴打击" },
    [452201]  = { index = 32, name = "狂风怒号" },
    [117014]  = { index = 33, name = "元素冲击" },
    [462620]  = { index = 34, name = "地震术" },
    [8042]    = { index = 35, name = "大地震击" },
    [191634]  = { index = 36, name = "风暴守护者" },
    [192106]  = { index = 37, name = "闪电之盾" },
    [77472]   = { index = 38, name = "治疗波" },
    [1064]    = { index = 39, name = "治疗链" },
    [61295]   = { index = 40, name = "激流" },
    [974]     = { index = 41, name = "大地之盾" },
    [77130]   = { index = 42, name = "净化灵魂" },
    [73685]   = { index = 43, name = "生命释放" },
    [1267068] = { index = 44, name = "风暴涌流图腾" },
    [73920]   = { index = 45, name = "治疗之雨" },
    [462603]  = { index = 46, name = "倾盆大雨" },
    [192077]  = { index = 47, name = "狂风图腾" },
    [456366]  = { index = 48, name = "治疗之雨" },
    [79206]   = { index = 49, name = "灵魂行者的恩赐" },
    [108271]  = { index = 50, name = "星界转移" },
    [2645]    = { index = 51, name = "幽魂之狼" },
    [370]     = { index = 52, name = "净化术" },
    [378773]  = { index = 53, name = "强效净化术" },
}
