if UnitClassBase("player") ~= "WARRIOR" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "敌人数量",
            },
            ["能量"] = {
                "怒气值",
            },
            ["目标"] = {
                "类型",
                "生命值",
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["焦点"] = {
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["配置开关"] = {
                "爆发开关",
                "输出模式",
                "AOE开关",
                "爆发药水开关",
            },
            ["物品"] = {
                "鲁莽药水",
            },
        },
        auras = {
            player = {
                { name = "天神下凡", spellId = 107574, },
                { name = "猝死", spellId = 52437 },
                { name = "破坏者", spellId = 228920 },
                { name = "间接伤害", spellId = 334783 },
                { name = "巨人神力", spellId = 440989, maxApps = 10 },
                { name = "侩子手的精准", spellId = 386633, maxApps = 2 },
                { name = "英勇之力", spellId = 1292058, maxApps = 5 },
                { name = "战争大师", spellId = 1269394, maxApps = 5 },
                { name = "横扫攻击", spellId = 260708, maxApps = 12 },
                { name = "粉碎连击", spellId = 1261189, maxApps = 2 },
            },
            target = {
                harmful = {
                    { name = "撕裂", spellId = 388539, },
                    { name = "巨人打击", spellId = 208086, },
                    { name = "重伤", spellId = 262115, },
                    { name = "崩毁", spellId = 447513, maxApps = 10 },
                },

            },
            focus = {
                harmful = {
                    { name = "撕裂", spellId = 388539, },
                    { name = "巨人打击", spellId = 208086, },
                    { name = "重伤", spellId = 262115, },
                    { name = "崩毁", spellId = 447513, maxApps = 10 },
                },
            },
        },
        spells = {
            { spellId = 202168, name = "胜利在望" },
            { spellId = 376079, name = "勇士之矛" },
            { spellId = 6544, name = "英勇飞跃" },
            { spellId = 97462, name = "集结呐喊" },
            { spellId = 46968, name = "震荡波" },
            { spellId = 107570, name = "风暴之锤" },
            { spellId = 384110, name = "破裂投掷" },
            { spellId = 64382, name = "碎裂投掷" },
            { spellId = 5246, name = "破胆怒吼" },
            { spellId = 7384, name = "压制", charge = true, maxCharge = 2 },
            { spellId = 163201, name = "斩杀" },
            { spellId = 845, name = "顺劈斩" },
            { spellId = 12294, name = "致死打击" },
            { spellId = 167105, name = "巨人打击" },
            { spellId = 436358, name = "崩摧" },
            { spellId = 6552, name = "拳击" },
            { spellId = 118038, name = "剑在人在" },
        },
    },
    [2] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "敌人数量",
            },
            ["能量"] = {
                "怒气值",
            },
            ["目标"] = {
                "类型",
                "生命值",
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["焦点"] = {
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
        },
        spells = {
            { spellId = 202168, name = "胜利在望" },
            { spellId = 376079, name = "勇士之矛" },
            { spellId = 6544, name = "英勇飞跃" },
            { spellId = 97462, name = "集结呐喊" },
            { spellId = 46968, name = "震荡波" },
            { spellId = 107570, name = "风暴之锤" },
            { spellId = 384110, name = "破裂投掷" },
            { spellId = 64382, name = "碎裂投掷" },
            { spellId = 5246, name = "破胆怒吼" },
            { spellId = 1719, name = "鲁莽" },
            { spellId = 6552, name = "拳击" },
        },
    },
    [3] = {
        states = {
            ["状态"] = {
                "锚点",
                "职业",
                "专精",
                "队伍类型",
                "英雄天赋",
                "有效性",
                "一键辅助",
                "插入法术",
                "战斗时间",
                "移动",
                "生命值",
                "队伍人数",
                "首领战",
                "难度",
                "敌人数量",
            },
            ["能量"] = {
                "怒气值",
            },
            ["目标"] = {
                "类型",
                "生命值",
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
            ["焦点"] = {
                "施法",
                "施法可打断",
                "引导",
                "引导可打断",
            },
        },
        -- TODO spellId: 盾牌格挡
        spells = {
            { spellId = 202168, name = "胜利在望" },
            { spellId = 376079, name = "勇士之矛" },
            { spellId = 6544, name = "英勇飞跃" },
            { spellId = 97462, name = "集结呐喊" },
            { spellId = 46968, name = "震荡波" },
            { spellId = 107570, name = "风暴之锤" },
            { spellId = 384110, name = "破裂投掷" },
            { spellId = 64382, name = "碎裂投掷" },
            { spellId = 5246, name = "破胆怒吼" },
            { spellId = 2565, name = "盾牌格挡", charge = true },
            { spellId = 385952, name = "盾牌冲锋" },
            { spellId = 107574, name = "天神下凡" },
            { spellId = 1160, name = "挫志怒吼" },
            { spellId = 6552, name = "拳击" },
            { spellId = 190456, name = "无视苦痛" },
        },
    },
}

Fuyutsui.spellsList = {
    [384255]  = { index = 151, name = "切换天赋" },
    [200749]  = { index = 152, name = "切换专精" },
    -- 种族（主动技能；同类技能多职业变体共用同一 index）
    [28730]   = { index = 101, name = "奥术洪流" },
    [25046]   = { index = 101, name = "奥术洪流" },
    [50613]   = { index = 101, name = "奥术洪流" },
    [69179]   = { index = 101, name = "奥术洪流" },
    [80483]   = { index = 101, name = "奥术洪流" },
    [129597]  = { index = 101, name = "奥术洪流" },
    [155145]  = { index = 101, name = "奥术洪流" },
    [202719]  = { index = 101, name = "奥术洪流" },
    [232633]  = { index = 101, name = "奥术洪流" },
    [20594]   = { index = 102, name = "石像形态" },
    [58984]   = { index = 103, name = "影遁" },
    [26297]   = { index = 104, name = "狂暴" },
    [20572]   = { index = 105, name = "血性狂怒" },
    [33697]   = { index = 105, name = "血性狂怒" },
    [33702]   = { index = 105, name = "血性狂怒" },
    [20549]   = { index = 106, name = "战争践踏" },
    [59752]   = { index = 107, name = "生存意志" },
    [7744]    = { index = 108, name = "亡灵意志" },
    [20589]   = { index = 109, name = "逃命专家" },
    [68992]   = { index = 110, name = "黑暗飞行" },
    [69070]   = { index = 111, name = "火箭跳" },
    [69041]   = { index = 112, name = "火箭弹幕" },
    [256948]  = { index = 113, name = "空间裂隙" },
    [255647]  = { index = 114, name = "圣光裁决" },
    [274738]  = { index = 115, name = "先祖召唤" },
    [265221]  = { index = 116, name = "烈焰之血" },
    [255654]  = { index = 117, name = "蛮牛冲撞" },
    [255723]  = { index = 117, name = "蛮牛冲撞" },
    [260364]  = { index = 118, name = "奥术脉冲" },
    [312411]  = { index = 119, name = "袋里乾坤" },
    [291944]  = { index = 120, name = "再生" },
    [107079]  = { index = 121, name = "震山掌" },
    [28880]   = { index = 122, name = "纳鲁的赐福" },
    [59542]   = { index = 122, name = "纳鲁的赐福" },
    [59543]   = { index = 122, name = "纳鲁的赐福" },
    [59544]   = { index = 122, name = "纳鲁的赐福" },
    [59545]   = { index = 122, name = "纳鲁的赐福" },
    [59547]   = { index = 122, name = "纳鲁的赐福" },
    [121093]  = { index = 122, name = "纳鲁的赐福" },
    [287712]  = { index = 123, name = "重拳出击" },
    [312924]  = { index = 124, name = "超有机光发起源" },
    [368970]  = { index = 125, name = "扫尾" },
    [357214]  = { index = 126, name = "翼击" },
    [436344]  = { index = 127, name = "艾泽里特涌动" },
    -- 战士
    [202168]  = { index = 1, name = "胜利在望" },
    [376079]  = { index = 2, name = "勇士之矛" },
    [6544]    = { index = 3, name = "英勇飞跃" },
    [97462]   = { index = 4, name = "集结呐喊" },
    [46968]   = { index = 5, name = "震荡波" },
    [107570]  = { index = 6, name = "风暴之锤" },
    [384110]  = { index = 7, name = "破裂投掷" },
    [64382]   = { index = 8, name = "碎裂投掷" },
    [5246]    = { index = 9, name = "破胆怒吼" },
    [385952]  = { index = 10, name = "盾牌冲锋" },
    [57755]   = { index = 11, name = "英勇投掷" },
    [6673]    = { index = 12, name = "战斗怒吼" },
    [1464]    = { index = 13, name = "猛击" },
    [772]     = { index = 14, name = "撕裂" },
    [281000]  = { index = 15, name = "斩杀" },
    [227847]  = { index = 16, name = "剑刃风暴" },
    [436358]  = { index = 17, name = "崩摧" },
    [12294]   = { index = 18, name = "致死打击" },
    [167105]  = { index = 19, name = "巨人打击" },
    [845]     = { index = 20, name = "顺劈斩" },
    [7384]    = { index = 21, name = "压制" },
    [260708]  = { index = 22, name = "横扫攻击" },
    [107574]  = { index = 23, name = "天神下凡" },
    [190411]  = { index = 24, name = "旋风斩" },
    [5308]    = { index = 25, name = "斩杀" },
    [23881]   = { index = 26, name = "嗜血" },
    [184367]  = { index = 27, name = "暴怒" },
    [385059]  = { index = 28, name = "奥丁之怒" },
    [85288]   = { index = 29, name = "怒击" },
    [6343]    = { index = 30, name = "雷霆一击" },
    [435222]  = { index = 31, name = "雷霆轰击" },
    [6572]    = { index = 32, name = "复仇" },
    [23922]   = { index = 33, name = "盾牌猛击" },
    [163201]  = { index = 34, name = "斩杀" },
    [1269383] = { index = 35, name = "英勇打击" },
    [335096]  = { index = 36, name = "浴血奋战" },
    [335100]  = { index = 37, name = "碎甲猛击" },
    [228920]  = { index = 38, name = "破坏者" },
    [280735]  = { index = 39, name = "斩杀（点了屠杀天赋）" },
}
